### ISSUE TITLE
Upgrade dependency sentry/sentry

### ISSUE THREAD

**Issue by jelen07** [Salamek/raven-nette#11]
Project require old version of `sentry/sentry` >=0.11.0.
`1.8.2` is available https://packagist.org/packages/sentry/sentry

**Comment by Salamek** [comment]
@jelen07 no, project require anything from 0.11.0 to latest release:

```bash
$ composer require salamek/raven-nette

Using version ^1.3 for salamek/raven-nette
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 3 installs, 0 updates, 0 removals
  - Installing sentry/sentry (1.8.2): Loading from cache
  - Installing tracy/tracy (v2.4.10): Loading from cache
  - Installing salamek/raven-nette (v1.3.3): Loading from cache
sentry/sentry suggests installing monolog/monolog (Automatically capture Monolog events as breadcrumbs)
tracy/tracy suggests installing https://nette.org/donate (Please support Tracy via a donation)
Writing lock file
Generating autoload files
```
As you can see, sentry/sentry (1.8.2) is installed.

So if you are getting older versions when installing this project, it means your env or other depedencies are incompatible with latest version of `sentry/sentry`

**Comment by jelen07** [comment]
You're right. Sorry for that 😉

**Comment by Salamek** [comment]
@jelen07 it is ok :smile_cat:, you can close this issue if that ^ is everything
