### ISSUE TITLE
Does not work in production mode

### ISSUE THREAD

**Issue by jelen07** [Salamek/raven-nette#12]
It does not log errors in production mode. For example if i throw `new \Exception()` in component render() method, Sentry is empty but log directory contain the exception.

**Comment by Salamek** [comment]
@jelen07 yea, log() and onFatalError() are not triggered in production for some reason... looks like new versions of nette are not compatible ?
I'm thinking about deprecating this project and suggest to use https://github.com/Kdyby/Monolog (monolog supports sentry)...

Or is there any sane reason to use this project (and fix this bug) ? (Just asking before deprecating this)

**Comment by jelen07** [comment]
This repo should not be used in production. We have already migrated to the `Kdyby/Monolog`.
