### ISSUE TITLE
Coding style

### ISSUE THREAD

**Issue by marten-cz** [Salamek/raven-nette#5]
Hi, I would like to clean the files and choose one coding style for them.
- do you want to use tabs or spaces?
- do you want to write constants in upper case or lower case (TRUE vs true)
- how many empty lines between methods and after class start and before class end?

I have some functional changes but I would like to solve this first. What about using PSR?

**Comment by Salamek** [comment]
@marten-cz 
- spaces
- hmm i'm using lowercase... but... well we can go with PSR

**Comment by marten-cz** [comment]
In SentryLogger.php there are both options. Lowercase in __construct() and uppercase in log(). PSR has lowercase (I think). I'll change my method and log() to have same coding style.

**Comment by Salamek** [comment]
@marten-cz any PR or should i fix it ? :)

**Comment by marten-cz** [comment]
@Salamek didn't had a time, go for it :-)

**Comment by Salamek** [comment]
@marten-cz can you review https://github.com/Salamek/raven-nette/pull/7 ? if is ok by you...

**Comment by marten-cz** [comment]
@Salamek looks good
